import { resolve, join } from 'node:path';
import { mkdir, copyFile, access, readFile } from 'node:fs/promises';
const target = process.argv[2] ?? process.env.OBSIDIAN_VAULT;
if (!target) throw Error('Specify an existing vault: npm run install:dev -- "path/to/vault" (or set OBSIDIAN_VAULT).');
const vault = resolve(target);
await access(join(vault, '.obsidian'));
const manifest = JSON.parse(await readFile('dist/manifest.json', 'utf8'));
if (manifest.id !== 'deepseedian') throw Error('Build the renamed plugin before installing: npm run build');
const destination = join(vault, '.obsidian/plugins', manifest.id);
await mkdir(destination, { recursive: true });
for (const file of ['main.js', 'manifest.json', 'styles.css', 'bridge.mjs', 'THIRD-PARTY-NOTICES.txt']) await copyFile(join('dist', file), join(destination, file));
console.log(`Installed ${destination}. Enable Deepseedian in Obsidian community plugins.`);
